services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: bookstore-sqlserver
    user: "0:0" # 👈 Tối ưu 1: Cấp quyền Root để trị dứt điểm lỗi Permission Denied
    restart: always
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./Backups:/var/opt/mssql/backup

  backend:
    build: ./backend/BookStore.API
    container_name: bookstore-backend
    restart: always
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BookStoreDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Backups:/app/backups

  frontend:
    build:
      context: ./frontend
      args:
        # 👈 Tối ưu 2: Biến động. Nếu không khai báo, tự động hiểu là localhost
        VITE_API_URL: ${VITE_API_URL:-http://localhost:5000/api}
    container_name: bookstore-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  sqlserver_data: