// <auto-generated />
using System;
using BookStore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStore.API.Models.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaCtHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MACTHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtHd"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DONGIA");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MAHOADON");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MASACH");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TONGTIEN");

                    b.HasKey("MaCtHd");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaSach");

                    b.ToTable("CHITIETHOADON");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("MaCtPn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MACTPN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtPn"));

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GIANHAP");

                    b.Property<string>("MaPhieuNhap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MAPHIEUNHAP");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MASACH");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONGNHAP");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("THANHTIEN");

                    b.HasKey("MaCtPn");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaSach");

                    b.ToTable("CHITIETPHIEUNHAP");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.DanhMuc", b =>
                {
                    b.Property<string>("MaDanhMuc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MADANHMUC");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MOTA");

                    b.Property<string>("ParentId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PARENTID");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SLUG");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENDANHMUC");

                    b.HasKey("MaDanhMuc");

                    b.HasIndex("ParentId");

                    b.ToTable("DANHMUC");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAGIOHANG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MAKHACHHANG");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MASACH");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.HasKey("MaGioHang");

                    b.HasIndex("MaSach");

                    b.HasIndex("MaKhachHang", "MaSach")
                        .IsUnique();

                    b.ToTable("GIOHANG");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.Gom", b =>
                {
                    b.Property<string>("MaSach")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MASACH");

                    b.Property<string>("MaDanhMuc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MADANHMUC");

                    b.HasKey("MaSach", "MaDanhMuc");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("GOM");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MAHOADON");

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DIACHIGIAOHANG");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GHICHU");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GIAMGIA");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MAKHACHHANG");

                    b.Property<string>("MaKhuyenMai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MAKHUYENMAI");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MANHANVIEN");

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYDATHANG");

                    b.Property<DateTime?>("NgayGiaoHang")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYGIAHANG");

                    b.Property<decimal>("PhiVanChuyen")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PHIVANCHUYEN");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PHUONGTHUCTHANHTOAN");

                    b.Property<string>("SoDienThoaiNhan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SODIENTHOAINHAN");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENNGUOINHAN");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TONGTIEN");

                    b.Property<string>("TrangThaiGiaoHang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TRANGTHAIGIAOHANG");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HOADON");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MAKHACHHANG");

                    b.Property<string>("DiaChiKh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DIACHIKH");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("HoTenKh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HOTENKH");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MATKHAU");

                    b.Property<DateTime>("NgayDk")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYDK");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SODIENTHOAI");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENDANGNHAP");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("KHACHHANG");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.KhuyenMai", b =>
                {
                    b.Property<string>("MaKhuyenMai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MAKHUYENMAI");

                    b.Property<bool>("LaGiveaway")
                        .HasColumnType("bit")
                        .HasColumnName("LAGIVEAWAY");

                    b.Property<string>("MaGiamGia")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MAGIAMGIA");

                    b.Property<decimal?>("MucGiam")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("MUCGIAM");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYBATDAU");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYKETTHUC");

                    b.HasKey("MaKhuyenMai");

                    b.ToTable("KHUYENMAI");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.NhaCungCap", b =>
                {
                    b.Property<string>("MaNhaCungCap")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MANHACUNGCAP");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MOTA");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TENNHACUNGCAP");

                    b.HasKey("MaNhaCungCap");

                    b.ToTable("NHACUNGCAP");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MANHANVIEN");

                    b.Property<string>("DiaChiNv")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DIACHINV");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MATKHAU");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ROLE");

                    b.Property<string>("SoDt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SODT");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENDANGNHAP");

                    b.Property<string>("TenNv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENNV");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAI");

                    b.Property<string>("TrangThaiLamViec")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TRANGTHAILAMVIEC");

                    b.Property<string>("VaiTroPhuTrach")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("VAITROPHUTRACH");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.PhieuNhap", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MAPHIEUNHAP");

                    b.Property<string>("MaNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MANHACUNGCAP");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MANHANVIEN");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2")
                        .HasColumnName("NGAYNHAP");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TONGTIEN");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaNhaCungCap");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PHIEUNHAP");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.Sach", b =>
                {
                    b.Property<string>("MaSach")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MASACH");

                    b.Property<string>("AnhSach")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ANHSACH");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GIABAN");

                    b.Property<int>("GiamGia")
                        .HasColumnType("int")
                        .HasColumnName("GIAMGIA");

                    b.Property<string>("HinhThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HINHTHUC");

                    b.Property<string>("KichThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KICHTHUOC");

                    b.Property<string>("LoaiSach")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOAISACH");

                    b.Property<string>("MaNhaCungCap")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MANHACUNGCAP");

                    b.Property<int?>("NamXuatBan")
                        .HasColumnType("int")
                        .HasColumnName("NAMXUATBAN");

                    b.Property<string>("NgonNgu")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("NGONNGU");

                    b.Property<string>("NguoiDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NGUOIDICH");

                    b.Property<string>("NhaCungCap")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NHACUNGCAP");

                    b.Property<string>("NhaXuatBan")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NHAXUATBAN");

                    b.Property<string>("NoiDungDemo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("NOIDUNGDEMO");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONGTON");

                    b.Property<int?>("SoTrang")
                        .HasColumnType("int")
                        .HasColumnName("SOTRANG");

                    b.Property<string>("TacGia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TACGIA");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TENSACH");

                    b.Property<int?>("TrongLuong")
                        .HasColumnType("int")
                        .HasColumnName("TRONGLUONG");

                    b.HasKey("MaSach");

                    b.ToTable("SACH");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("BookStore.API.Models.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.API.Models.Entities.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("BookStore.API.Models.Entities.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.API.Models.Entities.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.DanhMuc", b =>
                {
                    b.HasOne("BookStore.API.Models.Entities.DanhMuc", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.GioHang", b =>
                {
                    b.HasOne("BookStore.API.Models.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.API.Models.Entities.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.Gom", b =>
                {
                    b.HasOne("BookStore.API.Models.Entities.DanhMuc", "DanhMuc")
                        .WithMany("Gom")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.API.Models.Entities.Sach", "Sach")
                        .WithMany("Gom")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.HoaDon", b =>
                {
                    b.HasOne("BookStore.API.Models.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.API.Models.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("MaKhuyenMai")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BookStore.API.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KhachHang");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.PhieuNhap", b =>
                {
                    b.HasOne("BookStore.API.Models.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.API.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.DanhMuc", b =>
                {
                    b.Navigation("Gom");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("BookStore.API.Models.Entities.Sach", b =>
                {
                    b.Navigation("Gom");
                });
#pragma warning restore 612, 618
        }
    }
}
